version: '3.8'

services:
  smartwatch:
    build: .
    container_name: smartwatch
    ports:
      - "8080:8080"  # Tomcat port
      - "1434:1433"  # SQL Server port
    environment:
      # Environment variables for SQL Server
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AnPassw0rd@123
      - MSSQL_PID=Developer
      - MSSQL_TRUST_CERT=true
      - MSSQL_ENCRYPT=false
      # Environment variables for the web application
      - DB_HOST=localhost
      - DB_PORT=1434
      - DB_NAME=smartwatch
      - DB_USER=sa
      - DB_PASSWORD=AnPassw0rd@123
      - TrustServerCertificate=true

    volumes:
      - sqlserver_data:/var/opt/mssql  # Persistent data for SQL Server
    networks:
      - smartwatch_network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  smartwatch_network:
    driver: bridge

volumes:
  sqlserver_data: