# Use SQL Server 2022
FROM mcr.microsoft.com/mssql/server:2022-latest

# Create work directory
WORKDIR /usr/src/app

# Copy initialization script
COPY scripts/init.sql /usr/src/app/init.sql

# Create and copy a custom initialization script
COPY scripts/init-db.sh /usr/src/app/init-db.sh

# Set environment variables
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=YourStrong@Passw0rd

# Expose SQL Server port
EXPOSE 1433

USER root
RUN chmod +x /usr/src/app/init-db.sh

USER mssql
CMD /bin/bash /usr/src/app/init-db.sh