services:
  webapp:
    build: .
    container_name: smartwatch-webapp
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - smartwatch_network
    restart: on-failure

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smartwatch-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=CZR#1*QZMpN0zx0b
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./scripts:/scripts
    command: /bin/bash -c '/opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P CZR#1*QZMpN0zx0b -i /scripts/init.sql & wait'
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P CZR#1*QZMpN0zx0b -Q 'SELECT 1' || exit 1
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 3s
    networks:
      - smartwatch_network

networks:
  smartwatch_network:
    driver: bridge

volumes:
  sqlserver_data: