services:
  webapp:
    build: .
    container_name: smartwatch-webapp
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_NAME=smartwatch
      - DB_USER=sa
      - DB_PASSWORD=CZR#1*QZMpN0zx0b
    networks:
      - smartwatch_network
    restart: on-failure


  db:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: smartwatch-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=CZR#1*QZMpN0zx0b
      - MSSQL_PID=Developer
      - MSSQL_ENCRYPT=OPTIONAL
      - MSSQL_TRUST_CERT=true
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P CZR#1*QZMpN0zx0b -Q 'SELECT 1' -C -N || exit 1
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 3s
    networks:
      - smartwatch_network

networks:
  smartwatch_network:
    driver: bridge

volumes:
  sqlserver_data: