services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: smartwatch-webapp
    ports:
      - "8080:8080"
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_NAME: smartwatch
      DB_USER: sa
      DB_PASSWORD: "AnPassw0rd@123"
      TrustServerCertificate: "true"
    networks:
      - smartwatch_network
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: smartwatch-sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "AnPassw0rd@123"
      MSSQL_PID: "Developer"
      MSSQL_TRUST_CERT: "true"
      MSSQL_ENCRYPT: "false"
      MSSQL_TCP_PORT: "1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - smartwatch_network
    restart: on-failure
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "AnPassw0rd@123" -Q "SELECT 1" -C -N || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  smartwatch_network:
    driver: bridge

volumes:
  sqlserver_data: