version: '3.8'

services:
  smartwatch:
    build: .
    container_name: smartwatch
    ports:
      - "8080:8080"  # Tomcat port
      - "1433:1433"  # SQL Server port
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=CZR#1*QZMpN0zx0b
      - MSSQL_PID=Developer
      # Thêm các biến môi trường này
      - MSSQL_ENCRYPT=OPTIONAL
      - MSSQL_TRUST_CERT=true
      - DB_HOST=127.0.0.1
      - DB_PORT=1433
      - DB_NAME=smartwatch
      - DB_USER=sa
      - DB_PASSWORD=CZR#1*QZMpN0zx0b
      # Thêm biến môi trường cho ODBC
      - SQLCMDPASSWORD=CZR#1*QZMpN0zx0b
      - SQLCMDTRUSTSERVERCERTIFICATE=yes
    volumes:
      - sqlserver_data:/var/opt/mssql  # Persistent data for SQL Server
    networks:
      - smartwatch_network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  smartwatch_network:
    driver: bridge

volumes:
  sqlserver_data: