version: '3.8'

services:
  webapp:
    build: .
    container_name: smartwatch-webapp
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_NAME=smartwatch
      - DB_USER=sa
      - DB_PASSWORD=CZR#1*QZMpN0zx0b
    networks:
      - watchstore-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smartwatch-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=CZR#1*QZMpN0zx0b
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./scripts:/scripts
    healthcheck:
      test: "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P CZR#1*QZMpN0zx0b -Q 'SELECT 1' || exit 1"
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    command: >
      bash -c "
        curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc &&
        curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | tee /etc/apt/sources.list.d/mssql-release.list &&
        apt-get update &&
        ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev &&
        /opt/mssql/bin/sqlservr & sleep 30s &&
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'CZR#1*QZMpN0zx0b' -i /scripts/init.sql & wait
      "
    networks:
      - watchstore-network

networks:
  watchstore-network:
    driver: bridge

volumes:
  sqlserver_data: